global:
  tlsDisable: true

server:
  service:
    enabled: true
  ingress:
    enabled: true
    hosts: 
    - host: vault.apps.haas-436.pez.pivotal.io

  ha:
    enabled: true
    replicas: 3
ui:
  enabled: true

